


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."abater_fatura_ao_excluir_parcela"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  IF OLD.fatura_id IS NOT NULL THEN
    UPDATE faturas_cartao
    SET valor_total = GREATEST(COALESCE(valor_total, 0) - COALESCE(OLD.valor_parcela, 0), 0)
    WHERE id = OLD.fatura_id;
  END IF;

  RETURN OLD;
END;
$$;


ALTER FUNCTION "public"."abater_fatura_ao_excluir_parcela"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."manter_apenas_uma_conta_principal"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
begin

  if new.principal = true then

    update contas
    set principal = false
    where id <> new.id;

  end if;

  return new;

end;
$$;


ALTER FUNCTION "public"."manter_apenas_uma_conta_principal"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."cartoes" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL,
    "final_cartao" "text",
    "dia_fechamento" integer NOT NULL,
    "dia_vencimento" integer NOT NULL,
    "ativo" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "limite_total" numeric DEFAULT 0,
    "cartao_em_uso" boolean DEFAULT false,
    "saldo_utilizado_inicial" numeric(12,2) DEFAULT 0,
    "tipo_cartao" "text" DEFAULT 'proprio'::"text" NOT NULL,
    "responsavel_nome" "text",
    "observacoes" "text",
    CONSTRAINT "cartoes_tipo_cartao_check" CHECK (("tipo_cartao" = ANY (ARRAY['proprio'::"text", 'terceiro'::"text"])))
);


ALTER TABLE "public"."cartoes" OWNER TO "postgres";


ALTER TABLE "public"."cartoes" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."cartoes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."categorias" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL,
    "tipo" "text" DEFAULT 'saida'::"text" NOT NULL,
    "grupo" "text",
    "operacional" boolean DEFAULT false NOT NULL,
    "uso" "text" DEFAULT 'geral'::"text" NOT NULL,
    "ativo" boolean DEFAULT true NOT NULL,
    "ordem" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "cor" "text",
    "icone" "text",
    "tipo_uso" "text" DEFAULT 'rateada'::"text"
);


ALTER TABLE "public"."categorias" OWNER TO "postgres";


ALTER TABLE "public"."categorias" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categorias_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."contas" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL,
    "instituicao" "text",
    "saldo_inicial" numeric(10,2) DEFAULT 0,
    "principal" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "ativo" boolean DEFAULT true,
    "permitir_saldo_negativo" boolean DEFAULT true,
    "limite_cheque_especial" numeric DEFAULT 0,
    "tipo_conta" "text" DEFAULT 'banco'::"text",
    "tipo_tag" "text",
    "recarga_automatica" boolean DEFAULT false,
    "valor_recarga_automatica" numeric(12,2) DEFAULT 0,
    "percentual_alerta_recarga" numeric(5,2) DEFAULT 30,
    "conta_recarga_id" bigint,
    "cartao_recarga_id" bigint,
    "veiculo_id" bigint,
    "tag_forma_recarga" "text",
    "tag_conta_recarga_id" bigint,
    "tag_cartao_recarga_id" bigint,
    "finalidade" "text" DEFAULT 'trabalho'::"text"
);


ALTER TABLE "public"."contas" OWNER TO "postgres";


ALTER TABLE "public"."contas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."contas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."entrada_plataformas" (
    "id" bigint NOT NULL,
    "entrada_id" bigint,
    "plataforma_id" bigint,
    "faturamento" numeric(10,2) DEFAULT 0,
    "numero_corridas" integer DEFAULT 0,
    "houve_pedagio" boolean DEFAULT false,
    "valor_reembolso" numeric(10,2) DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."entrada_plataformas" OWNER TO "postgres";


ALTER TABLE "public"."entrada_plataformas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."entrada_plataformas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."entradas" (
    "id" bigint NOT NULL,
    "data" "date" NOT NULL,
    "horas_trabalhadas" interval,
    "km_rodados" numeric(10,2),
    "conta_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "veiculo_id" bigint,
    "custo_estimado_combustivel" numeric DEFAULT 0
);


ALTER TABLE "public"."entradas" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."entradas_avulsas" (
    "id" bigint NOT NULL,
    "data" "date" NOT NULL,
    "conta_id" bigint,
    "valor" numeric(12,2) NOT NULL,
    "descricao" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "finalidade" "text",
    "renegociacao_id" bigint
);


ALTER TABLE "public"."entradas_avulsas" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."entradas_avulsas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."entradas_avulsas_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."entradas_avulsas_id_seq" OWNED BY "public"."entradas_avulsas"."id";



ALTER TABLE "public"."entradas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."entradas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."faturas_cartao" (
    "id" bigint NOT NULL,
    "cartao_id" bigint,
    "mes_referencia" integer,
    "ano_referencia" integer,
    "data_fechamento" "date",
    "data_vencimento_prevista" "date",
    "data_vencimento_real" "date",
    "valor_total" numeric DEFAULT 0,
    "status" "text" DEFAULT 'aberta'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "mes" integer,
    "ano" integer,
    "data_vencimento" "date",
    "valor_pago" numeric DEFAULT 0,
    "renegociacao_id" bigint
);


ALTER TABLE "public"."faturas_cartao" OWNER TO "postgres";


ALTER TABLE "public"."faturas_cartao" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."faturas_cartao_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."jornadas_pausas" (
    "id" bigint NOT NULL,
    "jornada_id" bigint,
    "inicio" timestamp with time zone NOT NULL,
    "fim" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."jornadas_pausas" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."jornadas_pausas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."jornadas_pausas_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."jornadas_pausas_id_seq" OWNED BY "public"."jornadas_pausas"."id";



CREATE TABLE IF NOT EXISTS "public"."jornadas_trabalho" (
    "id" bigint NOT NULL,
    "veiculo_id" bigint,
    "data" "date" DEFAULT CURRENT_DATE NOT NULL,
    "inicio" timestamp with time zone NOT NULL,
    "fim" timestamp with time zone,
    "status" "text" DEFAULT 'em_andamento'::"text" NOT NULL,
    "km_inicial" numeric(12,2),
    "km_final" numeric(12,2),
    "km_rodados" numeric(12,2),
    "total_pausas_segundos" integer DEFAULT 0,
    "observacao" "text",
    "lancamento_entrada_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."jornadas_trabalho" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."jornadas_trabalho_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."jornadas_trabalho_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."jornadas_trabalho_id_seq" OWNED BY "public"."jornadas_trabalho"."id";



CREATE TABLE IF NOT EXISTS "public"."manutencao_itens" (
    "id" bigint NOT NULL,
    "manutencao_id" bigint NOT NULL,
    "manutencao_servico_id" bigint,
    "descricao" "text" NOT NULL,
    "quantidade" numeric DEFAULT 1,
    "valor_estimado" numeric,
    "observacoes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."manutencao_itens" OWNER TO "postgres";


ALTER TABLE "public"."manutencao_itens" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."manutencao_itens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."manutencao_oficinas" (
    "id" bigint NOT NULL,
    "manutencao_id" bigint NOT NULL,
    "oficina_id" bigint,
    "nome" "text" NOT NULL,
    "valor_mao_obra" numeric,
    "observacoes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."manutencao_oficinas" OWNER TO "postgres";


ALTER TABLE "public"."manutencao_oficinas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."manutencao_oficinas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."manutencao_pagamento_itens" (
    "id" bigint NOT NULL,
    "manutencao_pagamento_id" bigint NOT NULL,
    "manutencao_item_id" bigint,
    "manutencao_oficina_id" bigint,
    "tipo_origem" "text" DEFAULT 'item'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."manutencao_pagamento_itens" OWNER TO "postgres";


ALTER TABLE "public"."manutencao_pagamento_itens" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."manutencao_pagamento_itens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."manutencao_pagamentos" (
    "id" bigint NOT NULL,
    "manutencao_id" bigint NOT NULL,
    "saida_id" bigint,
    "descricao" "text" NOT NULL,
    "valor_total" numeric DEFAULT 0 NOT NULL,
    "forma_pagamento" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."manutencao_pagamentos" OWNER TO "postgres";


ALTER TABLE "public"."manutencao_pagamentos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."manutencao_pagamentos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."manutencao_servicos" (
    "id" bigint NOT NULL,
    "manutencao_id" bigint NOT NULL,
    "servico_id" bigint,
    "nome" "text" NOT NULL,
    "periodicidade_km" numeric,
    "periodicidade_meses" integer,
    "proxima_revisao_km" numeric,
    "proxima_revisao_data" "date",
    "observacoes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."manutencao_servicos" OWNER TO "postgres";


ALTER TABLE "public"."manutencao_servicos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."manutencao_servicos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."manutencoes" (
    "id" bigint NOT NULL,
    "data" "date" NOT NULL,
    "veiculo_id" bigint,
    "odometro" numeric,
    "titulo" "text",
    "observacoes" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."manutencoes" OWNER TO "postgres";


ALTER TABLE "public"."manutencoes" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."manutencoes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."metas" (
    "id" bigint NOT NULL,
    "nome" "text" DEFAULT 'Meta principal'::"text",
    "tipo" "text" NOT NULL,
    "valor_base" numeric(12,2) NOT NULL,
    "mes" integer NOT NULL,
    "ano" integer NOT NULL,
    "dias_trabalho" integer[] DEFAULT '{}'::integer[],
    "ativa" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "data_inicio" "date" DEFAULT CURRENT_DATE,
    "valor_realizado_antes" numeric(12,2) DEFAULT 0,
    "dias_semana" "jsonb" DEFAULT '[]'::"jsonb",
    "dias_mes" "jsonb" DEFAULT '[]'::"jsonb",
    "configuracao" "jsonb" DEFAULT '{}'::"jsonb",
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."metas" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."metas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."metas_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."metas_id_seq" OWNED BY "public"."metas"."id";



CREATE TABLE IF NOT EXISTS "public"."oficinas_manutencao" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL,
    "observacoes" "text",
    "ativo" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."oficinas_manutencao" OWNER TO "postgres";


ALTER TABLE "public"."oficinas_manutencao" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."oficinas_manutencao_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."plataformas" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "logo_url" "text",
    "visivel" boolean DEFAULT true
);


ALTER TABLE "public"."plataformas" OWNER TO "postgres";


ALTER TABLE "public"."plataformas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."plataformas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."renegociacoes" (
    "id" bigint NOT NULL,
    "credor" "text" NOT NULL,
    "data_renegociacao" "date" NOT NULL,
    "forma_pagamento" "text" DEFAULT 'debito_conta'::"text" NOT NULL,
    "conta_debito_id" bigint,
    "conta_ajuste_id" bigint,
    "saldo_conta_apos" numeric,
    "valor_original" numeric DEFAULT 0 NOT NULL,
    "valor_renegociado" numeric DEFAULT 0 NOT NULL,
    "valor_entrada" numeric DEFAULT 0 NOT NULL,
    "numero_parcelas" integer DEFAULT 1 NOT NULL,
    "primeiro_vencimento" "date",
    "observacoes" "text",
    "status" "text" DEFAULT 'ativa'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."renegociacoes" OWNER TO "postgres";


ALTER TABLE "public"."renegociacoes" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."renegociacoes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."renegociacoes_itens" (
    "id" bigint NOT NULL,
    "renegociacao_id" bigint NOT NULL,
    "tipo_origem" "text" NOT NULL,
    "origem_id" bigint NOT NULL,
    "titulo" "text",
    "detalhe" "text",
    "tipo_renegociacao" "text" DEFAULT 'total'::"text" NOT NULL,
    "valor_original" numeric DEFAULT 0 NOT NULL,
    "valor_renegociado" numeric DEFAULT 0,
    "payload" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."renegociacoes_itens" OWNER TO "postgres";


ALTER TABLE "public"."renegociacoes_itens" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."renegociacoes_itens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."saidas" (
    "id" bigint NOT NULL,
    "data_compra" "date" NOT NULL,
    "forma_pagamento" "text" NOT NULL,
    "conta_id" bigint,
    "cartao_id" bigint,
    "tipo_credito" "text",
    "numero_parcelas" integer DEFAULT 1,
    "valor_total" numeric DEFAULT 0 NOT NULL,
    "valor_parcela" numeric DEFAULT 0,
    "data_efetivacao" "date",
    "categoria" "text" NOT NULL,
    "descricao" "text",
    "status" "text" DEFAULT 'pendente'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "fatura_pagamento_id" bigint,
    "tipo_movimentacao" "text" DEFAULT 'saida'::"text",
    "data_vencimento" "date",
    "saida_origem_id" bigint,
    "categoria_id" bigint,
    "finalidade" "text" DEFAULT 'trabalho'::"text",
    "valor_pago" numeric DEFAULT 0,
    "conta_pagar_origem_id" bigint,
    "renegociacao_id" bigint
);


ALTER TABLE "public"."saidas" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."saidas_abastecimentos" (
    "id" bigint NOT NULL,
    "saida_id" bigint,
    "veiculo_id" bigint,
    "odometro" numeric,
    "km_rodados" numeric,
    "tipo_combustivel" "text",
    "litros" numeric,
    "valor_litro" numeric,
    "tanque_cheio" boolean DEFAULT false,
    "uso" "text" DEFAULT 'trabalho'::"text",
    "percentual_trabalho" numeric DEFAULT 100,
    "posto" "text",
    "observacoes" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "km_total_periodo" numeric DEFAULT 0,
    "consumo_km_l" numeric DEFAULT 0,
    "custo_por_km" numeric DEFAULT 0
);


ALTER TABLE "public"."saidas_abastecimentos" OWNER TO "postgres";


ALTER TABLE "public"."saidas_abastecimentos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."saidas_abastecimentos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."saidas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."saidas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."saidas_manutencoes" (
    "id" bigint NOT NULL,
    "saida_id" bigint,
    "veiculo_id" bigint,
    "odometro" numeric,
    "tipo_manutencao" "text",
    "servico" "text",
    "oficina" "text",
    "proxima_revisao_km" numeric,
    "proxima_revisao_data" "date",
    "observacoes" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."saidas_manutencoes" OWNER TO "postgres";


ALTER TABLE "public"."saidas_manutencoes" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."saidas_manutencoes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."saidas_parcelas" (
    "id" bigint NOT NULL,
    "saida_id" bigint,
    "numero_parcela" integer NOT NULL,
    "valor_parcela" numeric DEFAULT 0 NOT NULL,
    "data_vencimento" "date",
    "status" "text" DEFAULT 'pendente'::"text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "fatura_id" bigint,
    "cartao_id" bigint,
    "total_parcelas" integer
);


ALTER TABLE "public"."saidas_parcelas" OWNER TO "postgres";


ALTER TABLE "public"."saidas_parcelas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."saidas_parcelas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."saidas_recargas_eletricas" (
    "id" bigint NOT NULL,
    "saida_id" bigint,
    "veiculo_id" bigint,
    "odometro" numeric,
    "km_rodados" numeric,
    "kwh" numeric,
    "valor_kwh" numeric,
    "local_recarga" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "custo_por_km" numeric DEFAULT 0,
    "consumo_km_kwh" numeric DEFAULT 0
);


ALTER TABLE "public"."saidas_recargas_eletricas" OWNER TO "postgres";


ALTER TABLE "public"."saidas_recargas_eletricas" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."saidas_recargas_eletricas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."saidas_tag" (
    "id" bigint NOT NULL,
    "saida_id" bigint,
    "conta_tag_id" bigint,
    "tipo_uso" "text" NOT NULL,
    "uso" "text",
    "descricao_local" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."saidas_tag" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."saidas_tag_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."saidas_tag_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."saidas_tag_id_seq" OWNED BY "public"."saidas_tag"."id";



CREATE TABLE IF NOT EXISTS "public"."servicos_manutencao" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL,
    "periodicidade_km" numeric,
    "periodicidade_meses" integer,
    "observacoes" "text",
    "ativo" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."servicos_manutencao" OWNER TO "postgres";


ALTER TABLE "public"."servicos_manutencao" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."servicos_manutencao_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."servicos_manutencao_itens" (
    "id" bigint NOT NULL,
    "servico_id" bigint NOT NULL,
    "descricao" "text" NOT NULL,
    "quantidade_padrao" numeric DEFAULT 1,
    "valor_padrao" numeric,
    "observacoes" "text",
    "ordem" integer DEFAULT 0,
    "ativo" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."servicos_manutencao_itens" OWNER TO "postgres";


ALTER TABLE "public"."servicos_manutencao_itens" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."servicos_manutencao_itens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."transferencias" (
    "id" bigint NOT NULL,
    "data" "date" NOT NULL,
    "conta_origem_id" bigint,
    "conta_destino_id" bigint,
    "valor" numeric(12,2) NOT NULL,
    "descricao" "text",
    "tipo" "text" DEFAULT 'transferencia'::"text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."transferencias" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."transferencias_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."transferencias_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."transferencias_id_seq" OWNED BY "public"."transferencias"."id";



CREATE TABLE IF NOT EXISTS "public"."veiculos" (
    "id" bigint NOT NULL,
    "nome" "text" NOT NULL,
    "marca" "text",
    "modelo" "text" NOT NULL,
    "ano" integer,
    "placa" "text",
    "odometro_atual" numeric DEFAULT 0,
    "principal" boolean DEFAULT false,
    "ativo" boolean DEFAULT true,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "odometro_inicial" numeric DEFAULT 0,
    "categoria_veiculo" "text" DEFAULT 'flex'::"text",
    "combustiveis_aceitos" "text"[] DEFAULT ARRAY['etanol'::"text", 'gasolina_comum'::"text", 'gasolina_aditivada'::"text"],
    "aceita_recarga_eletrica" boolean DEFAULT false,
    "media_etanol" numeric DEFAULT 0,
    "media_gasolina" numeric DEFAULT 0,
    "media_gnv" numeric DEFAULT 0,
    "media_diesel" numeric DEFAULT 0,
    "media_eletrica_km_kwh" numeric DEFAULT 0,
    "custo_medio_km_combustivel" numeric DEFAULT 0,
    "custo_medio_km_eletrico" numeric DEFAULT 0,
    "custo_medio_km_geral" numeric DEFAULT 0
);


ALTER TABLE "public"."veiculos" OWNER TO "postgres";


ALTER TABLE "public"."veiculos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."veiculos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."veiculos_protecoes" (
    "id" bigint NOT NULL,
    "veiculo_id" bigint NOT NULL,
    "tipo_protecao" "text" DEFAULT 'seguro'::"text" NOT NULL,
    "nome_protecao" "text" NOT NULL,
    "inicio_vigencia" "date" NOT NULL,
    "fim_vigencia" "date" NOT NULL,
    "forma_pagamento" "text" NOT NULL,
    "valor_total" numeric(12,2) DEFAULT 0 NOT NULL,
    "valor_parcela" numeric(12,2) DEFAULT 0 NOT NULL,
    "numero_parcelas" integer DEFAULT 1 NOT NULL,
    "parcelas_pagas" integer DEFAULT 0 NOT NULL,
    "primeiro_vencimento_pendente" "date",
    "conta_id" bigint,
    "cartao_id" bigint,
    "lancamentos_gerados" boolean DEFAULT false NOT NULL,
    "ativo" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."veiculos_protecoes" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."veiculos_protecoes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."veiculos_protecoes_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."veiculos_protecoes_id_seq" OWNED BY "public"."veiculos_protecoes"."id";



ALTER TABLE ONLY "public"."entradas_avulsas" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."entradas_avulsas_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."jornadas_pausas" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."jornadas_pausas_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."jornadas_trabalho" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."jornadas_trabalho_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."metas" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."metas_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."saidas_tag" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."saidas_tag_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."transferencias" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."transferencias_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."veiculos_protecoes" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."veiculos_protecoes_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."cartoes"
    ADD CONSTRAINT "cartoes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categorias"
    ADD CONSTRAINT "categorias_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."contas"
    ADD CONSTRAINT "contas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."entrada_plataformas"
    ADD CONSTRAINT "entrada_plataformas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."entradas_avulsas"
    ADD CONSTRAINT "entradas_avulsas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."entradas"
    ADD CONSTRAINT "entradas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."faturas_cartao"
    ADD CONSTRAINT "faturas_cartao_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."jornadas_pausas"
    ADD CONSTRAINT "jornadas_pausas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."jornadas_trabalho"
    ADD CONSTRAINT "jornadas_trabalho_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."manutencao_itens"
    ADD CONSTRAINT "manutencao_itens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."manutencao_oficinas"
    ADD CONSTRAINT "manutencao_oficinas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."manutencao_pagamento_itens"
    ADD CONSTRAINT "manutencao_pagamento_itens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."manutencao_pagamentos"
    ADD CONSTRAINT "manutencao_pagamentos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."manutencao_servicos"
    ADD CONSTRAINT "manutencao_servicos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."manutencoes"
    ADD CONSTRAINT "manutencoes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."metas"
    ADD CONSTRAINT "metas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."oficinas_manutencao"
    ADD CONSTRAINT "oficinas_manutencao_nome_unique" UNIQUE ("nome");



ALTER TABLE ONLY "public"."oficinas_manutencao"
    ADD CONSTRAINT "oficinas_manutencao_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."plataformas"
    ADD CONSTRAINT "plataformas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."renegociacoes_itens"
    ADD CONSTRAINT "renegociacoes_itens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."renegociacoes"
    ADD CONSTRAINT "renegociacoes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."saidas_abastecimentos"
    ADD CONSTRAINT "saidas_abastecimentos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."saidas_manutencoes"
    ADD CONSTRAINT "saidas_manutencoes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."saidas_parcelas"
    ADD CONSTRAINT "saidas_parcelas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."saidas"
    ADD CONSTRAINT "saidas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."saidas_recargas_eletricas"
    ADD CONSTRAINT "saidas_recargas_eletricas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."saidas_tag"
    ADD CONSTRAINT "saidas_tag_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."servicos_manutencao_itens"
    ADD CONSTRAINT "servicos_manutencao_itens_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."servicos_manutencao"
    ADD CONSTRAINT "servicos_manutencao_nome_unique" UNIQUE ("nome");



ALTER TABLE ONLY "public"."servicos_manutencao"
    ADD CONSTRAINT "servicos_manutencao_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."transferencias"
    ADD CONSTRAINT "transferencias_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."veiculos"
    ADD CONSTRAINT "veiculos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."veiculos_protecoes"
    ADD CONSTRAINT "veiculos_protecoes_pkey" PRIMARY KEY ("id");



CREATE UNIQUE INDEX "faturas_cartao_ativa_cartao_mes_ano_idx" ON "public"."faturas_cartao" USING "btree" ("cartao_id", "mes", "ano") WHERE ("status" = ANY (ARRAY['aberta'::"text", 'fechada'::"text", 'parcial'::"text"]));



CREATE INDEX "idx_entradas_avulsas_renegociacao" ON "public"."entradas_avulsas" USING "btree" ("renegociacao_id");



CREATE INDEX "idx_faturas_cartao_renegociacao" ON "public"."faturas_cartao" USING "btree" ("renegociacao_id");



CREATE INDEX "idx_manutencao_itens_manutencao" ON "public"."manutencao_itens" USING "btree" ("manutencao_id");



CREATE INDEX "idx_manutencao_pagamentos_manutencao" ON "public"."manutencao_pagamentos" USING "btree" ("manutencao_id");



CREATE INDEX "idx_manutencao_servicos_manutencao" ON "public"."manutencao_servicos" USING "btree" ("manutencao_id");



CREATE INDEX "idx_manutencoes_veiculo_data" ON "public"."manutencoes" USING "btree" ("veiculo_id", "data" DESC);



CREATE INDEX "idx_renegociacoes_data" ON "public"."renegociacoes" USING "btree" ("data_renegociacao");



CREATE INDEX "idx_renegociacoes_itens_renegociacao" ON "public"."renegociacoes_itens" USING "btree" ("renegociacao_id");



CREATE INDEX "idx_saidas_conta_pagar_origem_id" ON "public"."saidas" USING "btree" ("conta_pagar_origem_id");



CREATE INDEX "idx_saidas_fatura_pagamento_id" ON "public"."saidas" USING "btree" ("fatura_pagamento_id");



CREATE INDEX "idx_saidas_renegociacao" ON "public"."saidas" USING "btree" ("renegociacao_id");



CREATE INDEX "idx_veiculos_protecoes_ativo" ON "public"."veiculos_protecoes" USING "btree" ("ativo");



CREATE INDEX "idx_veiculos_protecoes_veiculo_id" ON "public"."veiculos_protecoes" USING "btree" ("veiculo_id");



CREATE UNIQUE INDEX "metas_tipo_unique_idx" ON "public"."metas" USING "btree" ("tipo") WHERE ("tipo" = ANY (ARRAY['diaria'::"text", 'semanal'::"text", 'mensal'::"text", 'anual'::"text"]));



CREATE OR REPLACE TRIGGER "trg_abater_fatura_ao_excluir_parcela" BEFORE DELETE ON "public"."saidas_parcelas" FOR EACH ROW EXECUTE FUNCTION "public"."abater_fatura_ao_excluir_parcela"();



CREATE OR REPLACE TRIGGER "trigger_manter_apenas_uma_conta_principal" BEFORE INSERT OR UPDATE ON "public"."contas" FOR EACH ROW EXECUTE FUNCTION "public"."manter_apenas_uma_conta_principal"();



ALTER TABLE ONLY "public"."contas"
    ADD CONSTRAINT "contas_cartao_recarga_id_fkey" FOREIGN KEY ("cartao_recarga_id") REFERENCES "public"."cartoes"("id");



ALTER TABLE ONLY "public"."contas"
    ADD CONSTRAINT "contas_conta_recarga_id_fkey" FOREIGN KEY ("conta_recarga_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."contas"
    ADD CONSTRAINT "contas_tag_cartao_recarga_id_fkey" FOREIGN KEY ("tag_cartao_recarga_id") REFERENCES "public"."cartoes"("id");



ALTER TABLE ONLY "public"."contas"
    ADD CONSTRAINT "contas_tag_conta_recarga_id_fkey" FOREIGN KEY ("tag_conta_recarga_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."contas"
    ADD CONSTRAINT "contas_veiculo_id_fkey" FOREIGN KEY ("veiculo_id") REFERENCES "public"."veiculos"("id");



ALTER TABLE ONLY "public"."entrada_plataformas"
    ADD CONSTRAINT "entrada_plataformas_entrada_id_fkey" FOREIGN KEY ("entrada_id") REFERENCES "public"."entradas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."entrada_plataformas"
    ADD CONSTRAINT "entrada_plataformas_plataforma_id_fkey" FOREIGN KEY ("plataforma_id") REFERENCES "public"."plataformas"("id");



ALTER TABLE ONLY "public"."entradas_avulsas"
    ADD CONSTRAINT "entradas_avulsas_conta_id_fkey" FOREIGN KEY ("conta_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."entradas_avulsas"
    ADD CONSTRAINT "entradas_avulsas_renegociacao_id_fkey" FOREIGN KEY ("renegociacao_id") REFERENCES "public"."renegociacoes"("id");



ALTER TABLE ONLY "public"."entradas"
    ADD CONSTRAINT "entradas_conta_id_fkey" FOREIGN KEY ("conta_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."entradas"
    ADD CONSTRAINT "entradas_veiculo_id_fkey" FOREIGN KEY ("veiculo_id") REFERENCES "public"."veiculos"("id");



ALTER TABLE ONLY "public"."faturas_cartao"
    ADD CONSTRAINT "faturas_cartao_cartao_id_fkey" FOREIGN KEY ("cartao_id") REFERENCES "public"."cartoes"("id");



ALTER TABLE ONLY "public"."faturas_cartao"
    ADD CONSTRAINT "faturas_cartao_renegociacao_id_fkey" FOREIGN KEY ("renegociacao_id") REFERENCES "public"."renegociacoes"("id");



ALTER TABLE ONLY "public"."jornadas_pausas"
    ADD CONSTRAINT "jornadas_pausas_jornada_id_fkey" FOREIGN KEY ("jornada_id") REFERENCES "public"."jornadas_trabalho"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."jornadas_trabalho"
    ADD CONSTRAINT "jornadas_trabalho_veiculo_id_fkey" FOREIGN KEY ("veiculo_id") REFERENCES "public"."veiculos"("id");



ALTER TABLE ONLY "public"."manutencao_itens"
    ADD CONSTRAINT "manutencao_itens_manutencao_id_fkey" FOREIGN KEY ("manutencao_id") REFERENCES "public"."manutencoes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."manutencao_itens"
    ADD CONSTRAINT "manutencao_itens_manutencao_servico_id_fkey" FOREIGN KEY ("manutencao_servico_id") REFERENCES "public"."manutencao_servicos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."manutencao_oficinas"
    ADD CONSTRAINT "manutencao_oficinas_manutencao_id_fkey" FOREIGN KEY ("manutencao_id") REFERENCES "public"."manutencoes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."manutencao_oficinas"
    ADD CONSTRAINT "manutencao_oficinas_oficina_id_fkey" FOREIGN KEY ("oficina_id") REFERENCES "public"."oficinas_manutencao"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."manutencao_pagamento_itens"
    ADD CONSTRAINT "manutencao_pagamento_itens_manutencao_item_id_fkey" FOREIGN KEY ("manutencao_item_id") REFERENCES "public"."manutencao_itens"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."manutencao_pagamento_itens"
    ADD CONSTRAINT "manutencao_pagamento_itens_manutencao_oficina_id_fkey" FOREIGN KEY ("manutencao_oficina_id") REFERENCES "public"."manutencao_oficinas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."manutencao_pagamento_itens"
    ADD CONSTRAINT "manutencao_pagamento_itens_manutencao_pagamento_id_fkey" FOREIGN KEY ("manutencao_pagamento_id") REFERENCES "public"."manutencao_pagamentos"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."manutencao_pagamentos"
    ADD CONSTRAINT "manutencao_pagamentos_manutencao_id_fkey" FOREIGN KEY ("manutencao_id") REFERENCES "public"."manutencoes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."manutencao_pagamentos"
    ADD CONSTRAINT "manutencao_pagamentos_saida_id_fkey" FOREIGN KEY ("saida_id") REFERENCES "public"."saidas"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."manutencao_servicos"
    ADD CONSTRAINT "manutencao_servicos_manutencao_id_fkey" FOREIGN KEY ("manutencao_id") REFERENCES "public"."manutencoes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."manutencao_servicos"
    ADD CONSTRAINT "manutencao_servicos_servico_id_fkey" FOREIGN KEY ("servico_id") REFERENCES "public"."servicos_manutencao"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."manutencoes"
    ADD CONSTRAINT "manutencoes_veiculo_id_fkey" FOREIGN KEY ("veiculo_id") REFERENCES "public"."veiculos"("id");



ALTER TABLE ONLY "public"."renegociacoes"
    ADD CONSTRAINT "renegociacoes_conta_ajuste_id_fkey" FOREIGN KEY ("conta_ajuste_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."renegociacoes"
    ADD CONSTRAINT "renegociacoes_conta_debito_id_fkey" FOREIGN KEY ("conta_debito_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."renegociacoes_itens"
    ADD CONSTRAINT "renegociacoes_itens_renegociacao_id_fkey" FOREIGN KEY ("renegociacao_id") REFERENCES "public"."renegociacoes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."saidas_abastecimentos"
    ADD CONSTRAINT "saidas_abastecimentos_saida_id_fkey" FOREIGN KEY ("saida_id") REFERENCES "public"."saidas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."saidas_abastecimentos"
    ADD CONSTRAINT "saidas_abastecimentos_veiculo_id_fkey" FOREIGN KEY ("veiculo_id") REFERENCES "public"."veiculos"("id");



ALTER TABLE ONLY "public"."saidas"
    ADD CONSTRAINT "saidas_cartao_id_fkey" FOREIGN KEY ("cartao_id") REFERENCES "public"."cartoes"("id");



ALTER TABLE ONLY "public"."saidas"
    ADD CONSTRAINT "saidas_categoria_id_fkey" FOREIGN KEY ("categoria_id") REFERENCES "public"."categorias"("id");



ALTER TABLE ONLY "public"."saidas"
    ADD CONSTRAINT "saidas_conta_id_fkey" FOREIGN KEY ("conta_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."saidas"
    ADD CONSTRAINT "saidas_fatura_pagamento_id_fkey" FOREIGN KEY ("fatura_pagamento_id") REFERENCES "public"."faturas_cartao"("id");



ALTER TABLE ONLY "public"."saidas_manutencoes"
    ADD CONSTRAINT "saidas_manutencoes_saida_id_fkey" FOREIGN KEY ("saida_id") REFERENCES "public"."saidas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."saidas_manutencoes"
    ADD CONSTRAINT "saidas_manutencoes_veiculo_id_fkey" FOREIGN KEY ("veiculo_id") REFERENCES "public"."veiculos"("id");



ALTER TABLE ONLY "public"."saidas_parcelas"
    ADD CONSTRAINT "saidas_parcelas_cartao_id_fkey" FOREIGN KEY ("cartao_id") REFERENCES "public"."cartoes"("id");



ALTER TABLE ONLY "public"."saidas_parcelas"
    ADD CONSTRAINT "saidas_parcelas_fatura_id_fkey" FOREIGN KEY ("fatura_id") REFERENCES "public"."faturas_cartao"("id");



ALTER TABLE ONLY "public"."saidas_parcelas"
    ADD CONSTRAINT "saidas_parcelas_saida_id_fkey" FOREIGN KEY ("saida_id") REFERENCES "public"."saidas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."saidas_recargas_eletricas"
    ADD CONSTRAINT "saidas_recargas_eletricas_saida_id_fkey" FOREIGN KEY ("saida_id") REFERENCES "public"."saidas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."saidas_recargas_eletricas"
    ADD CONSTRAINT "saidas_recargas_eletricas_veiculo_id_fkey" FOREIGN KEY ("veiculo_id") REFERENCES "public"."veiculos"("id");



ALTER TABLE ONLY "public"."saidas"
    ADD CONSTRAINT "saidas_renegociacao_id_fkey" FOREIGN KEY ("renegociacao_id") REFERENCES "public"."renegociacoes"("id");



ALTER TABLE ONLY "public"."saidas"
    ADD CONSTRAINT "saidas_saida_origem_id_fkey" FOREIGN KEY ("saida_origem_id") REFERENCES "public"."saidas"("id");



ALTER TABLE ONLY "public"."saidas_tag"
    ADD CONSTRAINT "saidas_tag_conta_tag_id_fkey" FOREIGN KEY ("conta_tag_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."saidas_tag"
    ADD CONSTRAINT "saidas_tag_saida_id_fkey" FOREIGN KEY ("saida_id") REFERENCES "public"."saidas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."servicos_manutencao_itens"
    ADD CONSTRAINT "servicos_manutencao_itens_servico_id_fkey" FOREIGN KEY ("servico_id") REFERENCES "public"."servicos_manutencao"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."transferencias"
    ADD CONSTRAINT "transferencias_conta_destino_id_fkey" FOREIGN KEY ("conta_destino_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."transferencias"
    ADD CONSTRAINT "transferencias_conta_origem_id_fkey" FOREIGN KEY ("conta_origem_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."veiculos_protecoes"
    ADD CONSTRAINT "veiculos_protecoes_cartao_id_fkey" FOREIGN KEY ("cartao_id") REFERENCES "public"."cartoes"("id");



ALTER TABLE ONLY "public"."veiculos_protecoes"
    ADD CONSTRAINT "veiculos_protecoes_conta_id_fkey" FOREIGN KEY ("conta_id") REFERENCES "public"."contas"("id");



ALTER TABLE ONLY "public"."veiculos_protecoes"
    ADD CONSTRAINT "veiculos_protecoes_veiculo_id_fkey" FOREIGN KEY ("veiculo_id") REFERENCES "public"."veiculos"("id") ON DELETE CASCADE;



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."abater_fatura_ao_excluir_parcela"() TO "anon";
GRANT ALL ON FUNCTION "public"."abater_fatura_ao_excluir_parcela"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."abater_fatura_ao_excluir_parcela"() TO "service_role";



GRANT ALL ON FUNCTION "public"."manter_apenas_uma_conta_principal"() TO "anon";
GRANT ALL ON FUNCTION "public"."manter_apenas_uma_conta_principal"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."manter_apenas_uma_conta_principal"() TO "service_role";



GRANT ALL ON TABLE "public"."cartoes" TO "anon";
GRANT ALL ON TABLE "public"."cartoes" TO "authenticated";
GRANT ALL ON TABLE "public"."cartoes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cartoes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cartoes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cartoes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."categorias" TO "anon";
GRANT ALL ON TABLE "public"."categorias" TO "authenticated";
GRANT ALL ON TABLE "public"."categorias" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categorias_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categorias_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categorias_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."contas" TO "anon";
GRANT ALL ON TABLE "public"."contas" TO "authenticated";
GRANT ALL ON TABLE "public"."contas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."contas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."entrada_plataformas" TO "anon";
GRANT ALL ON TABLE "public"."entrada_plataformas" TO "authenticated";
GRANT ALL ON TABLE "public"."entrada_plataformas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."entrada_plataformas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."entrada_plataformas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."entrada_plataformas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."entradas" TO "anon";
GRANT ALL ON TABLE "public"."entradas" TO "authenticated";
GRANT ALL ON TABLE "public"."entradas" TO "service_role";



GRANT ALL ON TABLE "public"."entradas_avulsas" TO "anon";
GRANT ALL ON TABLE "public"."entradas_avulsas" TO "authenticated";
GRANT ALL ON TABLE "public"."entradas_avulsas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."entradas_avulsas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."entradas_avulsas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."entradas_avulsas_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."entradas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."entradas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."entradas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."faturas_cartao" TO "anon";
GRANT ALL ON TABLE "public"."faturas_cartao" TO "authenticated";
GRANT ALL ON TABLE "public"."faturas_cartao" TO "service_role";



GRANT ALL ON SEQUENCE "public"."faturas_cartao_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."faturas_cartao_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."faturas_cartao_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."jornadas_pausas" TO "anon";
GRANT ALL ON TABLE "public"."jornadas_pausas" TO "authenticated";
GRANT ALL ON TABLE "public"."jornadas_pausas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."jornadas_pausas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."jornadas_pausas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."jornadas_pausas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."jornadas_trabalho" TO "anon";
GRANT ALL ON TABLE "public"."jornadas_trabalho" TO "authenticated";
GRANT ALL ON TABLE "public"."jornadas_trabalho" TO "service_role";



GRANT ALL ON SEQUENCE "public"."jornadas_trabalho_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."jornadas_trabalho_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."jornadas_trabalho_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."manutencao_itens" TO "anon";
GRANT ALL ON TABLE "public"."manutencao_itens" TO "authenticated";
GRANT ALL ON TABLE "public"."manutencao_itens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."manutencao_itens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."manutencao_itens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."manutencao_itens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."manutencao_oficinas" TO "anon";
GRANT ALL ON TABLE "public"."manutencao_oficinas" TO "authenticated";
GRANT ALL ON TABLE "public"."manutencao_oficinas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."manutencao_oficinas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."manutencao_oficinas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."manutencao_oficinas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."manutencao_pagamento_itens" TO "anon";
GRANT ALL ON TABLE "public"."manutencao_pagamento_itens" TO "authenticated";
GRANT ALL ON TABLE "public"."manutencao_pagamento_itens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."manutencao_pagamento_itens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."manutencao_pagamento_itens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."manutencao_pagamento_itens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."manutencao_pagamentos" TO "anon";
GRANT ALL ON TABLE "public"."manutencao_pagamentos" TO "authenticated";
GRANT ALL ON TABLE "public"."manutencao_pagamentos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."manutencao_pagamentos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."manutencao_pagamentos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."manutencao_pagamentos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."manutencao_servicos" TO "anon";
GRANT ALL ON TABLE "public"."manutencao_servicos" TO "authenticated";
GRANT ALL ON TABLE "public"."manutencao_servicos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."manutencao_servicos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."manutencao_servicos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."manutencao_servicos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."manutencoes" TO "anon";
GRANT ALL ON TABLE "public"."manutencoes" TO "authenticated";
GRANT ALL ON TABLE "public"."manutencoes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."manutencoes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."manutencoes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."manutencoes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."metas" TO "anon";
GRANT ALL ON TABLE "public"."metas" TO "authenticated";
GRANT ALL ON TABLE "public"."metas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."metas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."metas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."metas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."oficinas_manutencao" TO "anon";
GRANT ALL ON TABLE "public"."oficinas_manutencao" TO "authenticated";
GRANT ALL ON TABLE "public"."oficinas_manutencao" TO "service_role";



GRANT ALL ON SEQUENCE "public"."oficinas_manutencao_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."oficinas_manutencao_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."oficinas_manutencao_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."plataformas" TO "anon";
GRANT ALL ON TABLE "public"."plataformas" TO "authenticated";
GRANT ALL ON TABLE "public"."plataformas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."plataformas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."plataformas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."plataformas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."renegociacoes" TO "anon";
GRANT ALL ON TABLE "public"."renegociacoes" TO "authenticated";
GRANT ALL ON TABLE "public"."renegociacoes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."renegociacoes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."renegociacoes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."renegociacoes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."renegociacoes_itens" TO "anon";
GRANT ALL ON TABLE "public"."renegociacoes_itens" TO "authenticated";
GRANT ALL ON TABLE "public"."renegociacoes_itens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."renegociacoes_itens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."renegociacoes_itens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."renegociacoes_itens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."saidas" TO "anon";
GRANT ALL ON TABLE "public"."saidas" TO "authenticated";
GRANT ALL ON TABLE "public"."saidas" TO "service_role";



GRANT ALL ON TABLE "public"."saidas_abastecimentos" TO "anon";
GRANT ALL ON TABLE "public"."saidas_abastecimentos" TO "authenticated";
GRANT ALL ON TABLE "public"."saidas_abastecimentos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."saidas_abastecimentos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."saidas_abastecimentos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."saidas_abastecimentos_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."saidas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."saidas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."saidas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."saidas_manutencoes" TO "anon";
GRANT ALL ON TABLE "public"."saidas_manutencoes" TO "authenticated";
GRANT ALL ON TABLE "public"."saidas_manutencoes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."saidas_manutencoes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."saidas_manutencoes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."saidas_manutencoes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."saidas_parcelas" TO "anon";
GRANT ALL ON TABLE "public"."saidas_parcelas" TO "authenticated";
GRANT ALL ON TABLE "public"."saidas_parcelas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."saidas_parcelas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."saidas_parcelas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."saidas_parcelas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."saidas_recargas_eletricas" TO "anon";
GRANT ALL ON TABLE "public"."saidas_recargas_eletricas" TO "authenticated";
GRANT ALL ON TABLE "public"."saidas_recargas_eletricas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."saidas_recargas_eletricas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."saidas_recargas_eletricas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."saidas_recargas_eletricas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."saidas_tag" TO "anon";
GRANT ALL ON TABLE "public"."saidas_tag" TO "authenticated";
GRANT ALL ON TABLE "public"."saidas_tag" TO "service_role";



GRANT ALL ON SEQUENCE "public"."saidas_tag_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."saidas_tag_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."saidas_tag_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."servicos_manutencao" TO "anon";
GRANT ALL ON TABLE "public"."servicos_manutencao" TO "authenticated";
GRANT ALL ON TABLE "public"."servicos_manutencao" TO "service_role";



GRANT ALL ON SEQUENCE "public"."servicos_manutencao_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."servicos_manutencao_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."servicos_manutencao_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."servicos_manutencao_itens" TO "anon";
GRANT ALL ON TABLE "public"."servicos_manutencao_itens" TO "authenticated";
GRANT ALL ON TABLE "public"."servicos_manutencao_itens" TO "service_role";



GRANT ALL ON SEQUENCE "public"."servicos_manutencao_itens_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."servicos_manutencao_itens_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."servicos_manutencao_itens_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."transferencias" TO "anon";
GRANT ALL ON TABLE "public"."transferencias" TO "authenticated";
GRANT ALL ON TABLE "public"."transferencias" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transferencias_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."transferencias_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."transferencias_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."veiculos" TO "anon";
GRANT ALL ON TABLE "public"."veiculos" TO "authenticated";
GRANT ALL ON TABLE "public"."veiculos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."veiculos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."veiculos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."veiculos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."veiculos_protecoes" TO "anon";
GRANT ALL ON TABLE "public"."veiculos_protecoes" TO "authenticated";
GRANT ALL ON TABLE "public"."veiculos_protecoes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."veiculos_protecoes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."veiculos_protecoes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."veiculos_protecoes_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
