-- Central de Gestao do Veiculo.
-- Completa a modelagem patrimonial e documental sem duplicar contratos financeiros existentes.

alter table public.veiculos
  drop constraint if exists veiculos_situacao_aquisicao_check;

alter table public.veiculos
  add constraint veiculos_situacao_aquisicao_check
    check (
      situacao_aquisicao is null
      or (
        tipo_posse is not distinct from 'proprio'
        and situacao_aquisicao in ('quitado', 'financiado')
      )
    );

alter table public.veiculos_financiamentos
  add column saldo_devedor numeric(12,2) check (saldo_devedor is null or saldo_devedor >= 0);

create table public.veiculos_aquisicoes (
  id bigint generated by default as identity primary key,
  veiculo_id bigint not null references public.veiculos(id) on delete restrict,
  valor_pago numeric(12,2) check (valor_pago is null or valor_pago >= 0),
  valor_atual numeric(12,2) check (valor_atual is null or valor_atual >= 0),
  forma_aquisicao text,
  data_aquisicao date,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint veiculos_aquisicoes_veiculo_unique unique (veiculo_id)
);

create table public.veiculos_documentos (
  id bigint generated by default as identity primary key,
  veiculo_id bigint not null references public.veiculos(id) on delete restrict,
  tipo text not null check (tipo in ('ipva', 'licenciamento')),
  ano integer not null check (ano between 1900 and 2200),
  valor numeric(12,2) not null default 0 check (valor >= 0),
  status text not null default 'pendente' check (status in ('pago', 'pendente', 'parcelado', 'entrada_parcelas')),
  data_pagamento date,
  saida_id bigint references public.saidas(id) on delete set null,
  observacoes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint veiculos_documentos_pagamento_check check (
    (status = 'pago' and data_pagamento is not null)
    or (status in ('pendente', 'parcelado', 'entrada_parcelas') and data_pagamento is null)
  ),
  constraint veiculos_documentos_ano_unique unique (veiculo_id, tipo, ano)
);

create index idx_veiculos_documentos_veiculo_tipo_ano
  on public.veiculos_documentos (veiculo_id, tipo, ano desc);

-- Converte os lancamentos historicos inequivocamente identificados como IPVA/licenciamento.
insert into public.veiculos_documentos (
  veiculo_id, tipo, ano, valor, status, data_pagamento, saida_id, created_at, updated_at
)
select distinct on (s.veiculo_id, documento.tipo, extract(year from s.data_compra)::integer)
  s.veiculo_id,
  documento.tipo,
  extract(year from s.data_compra)::integer,
  greatest(coalesce(s.valor_total, 0), 0),
  case when lower(coalesce(s.status, '')) in ('pago', 'paga') then 'pago' else 'pendente' end,
  case when lower(coalesce(s.status, '')) in ('pago', 'paga') then coalesce(s.data_efetivacao, s.data_compra) else null end,
  s.id,
  coalesce(s.created_at, now()),
  now()
from public.saidas s
cross join lateral (
  select case
    when lower(coalesce(s.categoria, '') || ' ' || coalesce(s.descricao, '')) like '%ipva%' then 'ipva'
    when lower(coalesce(s.categoria, '') || ' ' || coalesce(s.descricao, '')) like '%licenciamento%' then 'licenciamento'
  end as tipo
) documento
where s.veiculo_id is not null
  and s.data_compra is not null
  and documento.tipo is not null
  and lower(coalesce(s.status, '')) not in ('cancelado', 'cancelada', 'excluido', 'excluida')
order by s.veiculo_id, documento.tipo, extract(year from s.data_compra)::integer, s.data_compra desc, s.id desc
on conflict (veiculo_id, tipo, ano) do nothing;

alter table public.veiculos_protecoes
  add column status text not null default 'ativa',
  add column encerrada_em date,
  add column substitui_protecao_id bigint references public.veiculos_protecoes(id) on delete restrict;

alter table public.veiculos_protecoes
  add constraint veiculos_protecoes_status_check
    check (status in ('ativa', 'cancelada', 'substituida', 'encerrada'));

update public.veiculos_protecoes
set status = case when ativo then 'ativa' else 'encerrada' end
where status is distinct from case when ativo then 'ativa' else 'encerrada' end;

create index idx_veiculos_protecoes_veiculo_historico
  on public.veiculos_protecoes (veiculo_id, created_at desc);

comment on table public.veiculos_aquisicoes is
  'Dados patrimoniais do veiculo proprio, separados do eventual contrato de financiamento.';
comment on table public.veiculos_documentos is
  'Historico anual normalizado de IPVA e licenciamento, preparado para integracao financeira.';
comment on column public.veiculos_documentos.saida_id is
  'Lancamento financeiro associado, quando existente; nao e criado automaticamente nesta fase.';

grant select, insert, update, delete on table public.veiculos_aquisicoes to anon, authenticated, service_role;
grant select, insert, update, delete on table public.veiculos_documentos to anon, authenticated, service_role;
grant usage, select on sequence public.veiculos_aquisicoes_id_seq to anon, authenticated, service_role;
grant usage, select on sequence public.veiculos_documentos_id_seq to anon, authenticated, service_role;
