-- Permite que Proteção seja o primeiro consumidor do contrato financeiro genérico.
-- Os cálculos de agenda continuam fora do banco e reutilizam o motor atual.

alter table public.contratos_financeiros
  drop constraint if exists contratos_financeiros_tipo_contrato_check;

alter table public.contratos_financeiros
  add constraint contratos_financeiros_tipo_contrato_check check (
    tipo_contrato in (
      'emprestimo',
      'financiamento',
      'leasing',
      'capital_giro',
      'consorcio',
      'antecipacao_recebiveis',
      'seguro',
      'protecao_veicular',
      'outro'
    )
  );

alter table public.contratos_financeiros
  add column nome text,
  add column contraparte_nome text,
  add column data_inicio date,
  add column data_fim date;

alter table public.contratos_financeiros
  alter column tipo_credor drop not null,
  alter column credor_nome drop not null,
  alter column valor_recebido drop not null,
  alter column valor_contratado drop not null,
  alter column data_contratacao drop not null,
  alter column data_recebimento drop not null,
  alter column conta_recebimento_id drop not null,
  alter column modo_pagamento drop not null,
  alter column quantidade_parcelas drop not null,
  alter column valor_parcela drop not null,
  alter column primeiro_vencimento drop not null,
  alter column periodicidade drop not null;

alter table public.contratos_financeiros
  add constraint contratos_financeiros_periodo_generico_check
  check (data_fim is null or data_inicio is null or data_fim >= data_inicio);

create table public.contratos_financeiros_planos_cobranca (
  id bigint generated by default as identity primary key,
  contrato_id bigint not null references public.contratos_financeiros(id) on delete restrict,
  papel text not null check (papel in ('principal', 'entrada', 'saldo', 'mensalidade')),
  tipo_agendamento text not null check (tipo_agendamento in ('unica', 'parcelada', 'recorrente')),
  ordem integer not null default 1 check (ordem > 0),
  valor_total numeric(14,2) check (valor_total is null or valor_total > 0),
  valor_cobranca numeric(14,2) not null check (valor_cobranca > 0),
  quantidade_cobrancas integer check (quantidade_cobrancas is null or quantidade_cobrancas > 0),
  primeiro_vencimento date not null,
  periodicidade text check (periodicidade is null or periodicidade in ('diaria', 'semanal', 'quinzenal', 'mensal', 'anual')),
  fim_recorrencia date,
  forma_pagamento_prevista text not null,
  conta_pagamento_id bigint references public.contas(id) on delete restrict,
  cartao_pagamento_id bigint references public.cartoes(id) on delete restrict,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contratos_planos_periodo_check check (
    fim_recorrencia is null or fim_recorrencia >= primeiro_vencimento
  ),
  constraint contratos_planos_agendamento_check check (
    (tipo_agendamento = 'unica' and quantidade_cobrancas = 1 and periodicidade is null)
    or (tipo_agendamento = 'parcelada' and quantidade_cobrancas >= 2 and periodicidade is not null)
    or (tipo_agendamento = 'recorrente' and periodicidade is not null and fim_recorrencia is not null)
  ),
  constraint contratos_planos_origem_check check (
    (
      forma_pagamento_prevista in ('credito_avista', 'credito_parcelado')
      and cartao_pagamento_id is not null
      and conta_pagamento_id is null
    )
    or (
      forma_pagamento_prevista = 'boleto'
      and cartao_pagamento_id is null
      and conta_pagamento_id is null
    )
    or (
      forma_pagamento_prevista not in ('credito_avista', 'credito_parcelado', 'boleto')
      and conta_pagamento_id is not null
      and cartao_pagamento_id is null
    )
  ),
  unique (contrato_id, ordem)
);

create index contratos_planos_contrato_ativo_idx
  on public.contratos_financeiros_planos_cobranca (contrato_id, ativo);

alter table public.contratos_financeiros_parcelas
  add column plano_cobranca_id bigint references public.contratos_financeiros_planos_cobranca(id) on delete restrict;

alter table public.contratos_financeiros_parcelas
  drop constraint if exists contratos_financeiros_parcelas_contrato_id_numero_key;

create unique index contratos_parcelas_legadas_numero_unique_idx
  on public.contratos_financeiros_parcelas (contrato_id, numero)
  where plano_cobranca_id is null;

create unique index contratos_parcelas_plano_numero_unique_idx
  on public.contratos_financeiros_parcelas (plano_cobranca_id, numero)
  where plano_cobranca_id is not null;

create index contratos_parcelas_plano_vencimento_idx
  on public.contratos_financeiros_parcelas (plano_cobranca_id, data_vencimento);

alter table public.veiculos_protecoes
  add column contrato_financeiro_id bigint references public.contratos_financeiros(id) on delete restrict;

create unique index veiculos_protecoes_contrato_financeiro_unique_idx
  on public.veiculos_protecoes (contrato_financeiro_id)
  where contrato_financeiro_id is not null;

alter table public.veiculos_protecoes
  drop constraint if exists veiculos_protecoes_status_check;

alter table public.veiculos_protecoes
  add constraint veiculos_protecoes_status_check
  check (status in ('ativa', 'cancelada', 'substituida', 'renovada', 'encerrada'));

comment on table public.contratos_financeiros_planos_cobranca is
  'Configuração declarativa de uma ou mais agendas de cobrança de um contrato financeiro.';
comment on column public.contratos_financeiros_parcelas.plano_cobranca_id is
  'Plano que originou a obrigação; a saída vinculada permanece como Conta a Pagar canônica.';

grant select, insert, update, delete on table public.contratos_financeiros_planos_cobranca
  to anon, authenticated, service_role;
grant usage, select on sequence public.contratos_financeiros_planos_cobranca_id_seq
  to anon, authenticated, service_role;
