-- Base genérica para contratos financeiros e suas obrigações.
-- Não altera nem faz backfill de registros existentes.

create table public.contratos_financeiros (
  id bigint generated by default as identity primary key,
  tipo_contrato text not null default 'emprestimo' check (
    tipo_contrato in (
      'emprestimo',
      'financiamento',
      'leasing',
      'capital_giro',
      'consorcio',
      'antecipacao_recebiveis',
      'outro'
    )
  ),
  tipo_credor text not null check (
    tipo_credor in ('banco', 'financeira', 'pessoa_fisica', 'empresa', 'outro')
  ),
  credor_nome text not null check (length(trim(credor_nome)) > 0),
  valor_recebido numeric(14,2) not null check (valor_recebido > 0),
  valor_contratado numeric(14,2) not null check (valor_contratado >= valor_recebido),
  taxa_juros_percentual numeric(9,4) not null default 0 check (taxa_juros_percentual >= 0),
  data_contratacao date not null,
  data_recebimento date not null,
  conta_recebimento_id bigint not null references public.contas(id) on delete restrict,
  descricao text,
  observacoes text,
  modo_pagamento text not null check (modo_pagamento in ('avista', 'parcelado')),
  quantidade_parcelas integer not null check (quantidade_parcelas > 0),
  valor_parcela numeric(14,2) not null check (valor_parcela > 0),
  primeiro_vencimento date not null,
  periodicidade text not null check (
    periodicidade in ('diaria', 'semanal', 'quinzenal', 'mensal')
  ),
  forma_pagamento text not null,
  conta_pagamento_id bigint references public.contas(id) on delete restrict,
  cartao_pagamento_id bigint references public.cartoes(id) on delete restrict,
  status text not null default 'ativo' check (
    status in ('ativo', 'quitado', 'cancelado')
  ),
  quitado_em date,
  cancelado_em date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contratos_financeiros_pagamento_check check (
    (
      forma_pagamento in ('credito_avista', 'credito_parcelado')
      and cartao_pagamento_id is not null
      and conta_pagamento_id is null
    )
    or (
      forma_pagamento not in ('credito_avista', 'credito_parcelado')
      and conta_pagamento_id is not null
      and cartao_pagamento_id is null
    )
  ),
  constraint contratos_financeiros_parcelamento_check check (
    (modo_pagamento = 'avista' and quantidade_parcelas = 1)
    or (modo_pagamento = 'parcelado' and quantidade_parcelas >= 2)
  )
);

create table public.contratos_financeiros_parcelas (
  id bigint generated by default as identity primary key,
  contrato_id bigint not null references public.contratos_financeiros(id) on delete restrict,
  numero integer not null check (numero > 0),
  data_vencimento date not null,
  valor numeric(14,2) not null check (valor > 0),
  valor_pago numeric(14,2) not null default 0 check (valor_pago >= 0 and valor_pago <= valor),
  status text not null default 'aberta' check (
    status in ('aberta', 'parcial', 'paga', 'cancelada')
  ),
  saida_id bigint unique references public.saidas(id) on delete restrict,
  cancelada_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (contrato_id, numero)
);

alter table public.entradas_avulsas
  add column contrato_financeiro_id bigint references public.contratos_financeiros(id) on delete restrict;

alter table public.saidas
  add column contrato_financeiro_id bigint references public.contratos_financeiros(id) on delete restrict,
  add column contrato_financeiro_parcela_id bigint references public.contratos_financeiros_parcelas(id) on delete restrict;

create unique index entradas_avulsas_contrato_financeiro_unique_idx
  on public.entradas_avulsas (contrato_financeiro_id)
  where contrato_financeiro_id is not null;

create index contratos_financeiros_tipo_status_idx
  on public.contratos_financeiros (tipo_contrato, status);
create index contratos_financeiros_conta_recebimento_idx
  on public.contratos_financeiros (conta_recebimento_id);
create index contratos_financeiros_parcelas_contrato_vencimento_idx
  on public.contratos_financeiros_parcelas (contrato_id, data_vencimento);
create index saidas_contrato_financeiro_idx
  on public.saidas (contrato_financeiro_id);
create unique index saidas_contrato_financeiro_parcela_unique_idx
  on public.saidas (contrato_financeiro_parcela_id)
  where contrato_financeiro_parcela_id is not null and tipo_movimentacao = 'conta_pagar';

create or replace function public.criar_contrato_financeiro(
  p_contrato jsonb,
  p_parcelas jsonb
)
returns bigint
language plpgsql
set search_path = public
as $$
declare
  v_contrato_id bigint;
  v_parcela_id bigint;
  v_saida_id bigint;
  v_parcela jsonb;
  v_total_parcelas numeric;
begin
  if jsonb_typeof(p_parcelas) <> 'array'
    or jsonb_array_length(p_parcelas) <> (p_contrato->>'quantidade_parcelas')::integer then
    raise exception 'A agenda de parcelas não corresponde à quantidade informada.';
  end if;

  select coalesce(sum((item->>'valor')::numeric), 0)
  into v_total_parcelas
  from jsonb_array_elements(p_parcelas) as item;

  if round(v_total_parcelas, 2) <> round((p_contrato->>'valor_contratado')::numeric, 2) then
    raise exception 'A soma das parcelas não corresponde ao valor contratado.';
  end if;

  insert into public.contratos_financeiros (
    tipo_contrato,
    tipo_credor,
    credor_nome,
    valor_recebido,
    valor_contratado,
    taxa_juros_percentual,
    data_contratacao,
    data_recebimento,
    conta_recebimento_id,
    descricao,
    observacoes,
    modo_pagamento,
    quantidade_parcelas,
    valor_parcela,
    primeiro_vencimento,
    periodicidade,
    forma_pagamento,
    conta_pagamento_id,
    cartao_pagamento_id
  ) values (
    coalesce(p_contrato->>'tipo_contrato', 'emprestimo'),
    p_contrato->>'tipo_credor',
    trim(p_contrato->>'credor_nome'),
    (p_contrato->>'valor_recebido')::numeric,
    (p_contrato->>'valor_contratado')::numeric,
    coalesce((p_contrato->>'taxa_juros_percentual')::numeric, 0),
    (p_contrato->>'data_contratacao')::date,
    (p_contrato->>'data_recebimento')::date,
    (p_contrato->>'conta_recebimento_id')::bigint,
    nullif(trim(p_contrato->>'descricao'), ''),
    nullif(trim(p_contrato->>'observacoes'), ''),
    p_contrato->>'modo_pagamento',
    (p_contrato->>'quantidade_parcelas')::integer,
    (p_contrato->>'valor_parcela')::numeric,
    (p_contrato->>'primeiro_vencimento')::date,
    p_contrato->>'periodicidade',
    p_contrato->>'forma_pagamento',
    nullif(p_contrato->>'conta_pagamento_id', '')::bigint,
    nullif(p_contrato->>'cartao_pagamento_id', '')::bigint
  ) returning id into v_contrato_id;

  insert into public.entradas_avulsas (
    data,
    conta_id,
    valor,
    descricao,
    finalidade,
    contrato_financeiro_id
  ) values (
    (p_contrato->>'data_recebimento')::date,
    (p_contrato->>'conta_recebimento_id')::bigint,
    (p_contrato->>'valor_recebido')::numeric,
    coalesce(nullif(trim(p_contrato->>'descricao'), ''), 'Empréstimo recebido - ' || trim(p_contrato->>'credor_nome')),
    null,
    v_contrato_id
  );

  for v_parcela in select value from jsonb_array_elements(p_parcelas)
  loop
    insert into public.contratos_financeiros_parcelas (
      contrato_id,
      numero,
      data_vencimento,
      valor
    ) values (
      v_contrato_id,
      (v_parcela->>'numero')::integer,
      (v_parcela->>'vencimento')::date,
      (v_parcela->>'valor')::numeric
    ) returning id into v_parcela_id;

    insert into public.saidas (
      data_compra,
      forma_pagamento,
      conta_id,
      cartao_id,
      numero_parcelas,
      valor_total,
      valor_parcela,
      categoria,
      descricao,
      status,
      tipo_movimentacao,
      data_vencimento,
      finalidade,
      contrato_financeiro_id,
      contrato_financeiro_parcela_id
    ) values (
      (v_parcela->>'vencimento')::date,
      p_contrato->>'forma_pagamento',
      nullif(p_contrato->>'conta_pagamento_id', '')::bigint,
      nullif(p_contrato->>'cartao_pagamento_id', '')::bigint,
      1,
      (v_parcela->>'valor')::numeric,
      (v_parcela->>'valor')::numeric,
      'Empréstimo',
      'Parcela ' || (v_parcela->>'numero') || '/' || (p_contrato->>'quantidade_parcelas') || ' - ' || trim(p_contrato->>'credor_nome'),
      'aberto',
      'conta_pagar',
      (v_parcela->>'vencimento')::date,
      null,
      v_contrato_id,
      v_parcela_id
    ) returning id into v_saida_id;

    update public.contratos_financeiros_parcelas
    set saida_id = v_saida_id
    where id = v_parcela_id;
  end loop;

  return v_contrato_id;
end;
$$;

comment on table public.contratos_financeiros is
  'Raiz genérica de empréstimos e futuros contratos financeiros.';
comment on table public.contratos_financeiros_parcelas is
  'Agenda canônica de obrigações de um contrato financeiro; saidas integra cada parcela ao fluxo financeiro.';

grant select, insert, update, delete on table public.contratos_financeiros to anon, authenticated, service_role;
grant select, insert, update, delete on table public.contratos_financeiros_parcelas to anon, authenticated, service_role;
grant usage, select on sequence public.contratos_financeiros_id_seq to anon, authenticated, service_role;
grant usage, select on sequence public.contratos_financeiros_parcelas_id_seq to anon, authenticated, service_role;
grant execute on function public.criar_contrato_financeiro(jsonb, jsonb) to anon, authenticated, service_role;
