-- MIGRATION DA SPRINT DE VEÍCULOS.
-- Mantém contratos separados dos lançamentos financeiros e não altera dados históricos.

create table public.veiculos_financiamentos (
  id bigint generated by default as identity primary key,
  veiculo_id bigint not null references public.veiculos(id) on delete restrict,
  instituicao_financeira text not null,
  valor_veiculo numeric(12,2) not null check (valor_veiculo > 0),
  valor_financiado numeric(12,2) not null check (valor_financiado > 0),
  valor_entrada numeric(12,2) not null default 0 check (valor_entrada >= 0),
  total_parcelas integer not null check (total_parcelas > 0),
  parcelas_pagas integer not null default 0 check (parcelas_pagas >= 0 and parcelas_pagas <= total_parcelas),
  numero_proxima_parcela integer,
  valor_parcela numeric(12,2) not null check (valor_parcela > 0),
  proximo_vencimento date,
  dia_vencimento integer check (dia_vencimento between 1 and 31),
  observacoes text,
  forma_pagamento text not null,
  conta_id bigint references public.contas(id) on delete restrict,
  cartao_id bigint references public.cartoes(id) on delete restrict,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint veiculos_financiamentos_proxima_parcela_check check (
    (parcelas_pagas = total_parcelas and numero_proxima_parcela is null and proximo_vencimento is null)
    or (
      parcelas_pagas < total_parcelas
      and numero_proxima_parcela between 1 and total_parcelas
      and numero_proxima_parcela > parcelas_pagas
      and proximo_vencimento is not null
    )
  ),
  constraint veiculos_financiamentos_origem_pagamento_check check (
    (forma_pagamento in ('credito_avista', 'credito_parcelado') and cartao_id is not null and conta_id is null)
    or (forma_pagamento not in ('credito_avista', 'credito_parcelado') and conta_id is not null and cartao_id is null)
  )
);

create unique index veiculos_financiamentos_ativo_veiculo_idx
  on public.veiculos_financiamentos (veiculo_id) where ativo;

create table public.veiculos_alugueis (
  id bigint generated by default as identity primary key,
  veiculo_id bigint not null references public.veiculos(id) on delete restrict,
  locador text not null,
  frequencia text not null check (frequencia in ('diaria', 'semanal', 'quinzenal', 'mensal', 'anual')),
  valor numeric(12,2) not null check (valor > 0),
  data_inicio date not null,
  proximo_vencimento date not null,
  dia_cobranca integer check (dia_cobranca between 1 and 31),
  data_fim date,
  observacoes text,
  forma_pagamento text,
  conta_id bigint references public.contas(id) on delete restrict,
  cartao_id bigint references public.cartoes(id) on delete restrict,
  desconto_plataforma boolean not null default false,
  plataforma_id bigint references public.plataformas(id) on delete restrict,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint veiculos_alugueis_periodo_check check (data_fim is null or data_fim >= data_inicio),
  constraint veiculos_alugueis_pagamento_check check (
    (desconto_plataforma and plataforma_id is not null and forma_pagamento is null and conta_id is null and cartao_id is null)
    or (
      not desconto_plataforma
      and plataforma_id is null
      and forma_pagamento is not null
      and (
        (forma_pagamento in ('credito_avista', 'credito_parcelado') and cartao_id is not null and conta_id is null)
        or (forma_pagamento not in ('credito_avista', 'credito_parcelado') and conta_id is not null and cartao_id is null)
      )
    )
  )
);

create unique index veiculos_alugueis_ativo_veiculo_idx
  on public.veiculos_alugueis (veiculo_id) where ativo;

create table public.veiculos_caucoes (
  id bigint generated by default as identity primary key,
  veiculo_id bigint not null references public.veiculos(id) on delete restrict,
  aluguel_id bigint not null references public.veiculos_alugueis(id) on delete restrict,
  valor numeric(12,2) not null check (valor > 0),
  data_pagamento date not null,
  forma_pagamento text not null,
  conta_id bigint references public.contas(id) on delete restrict,
  cartao_id bigint references public.cartoes(id) on delete restrict,
  devolvivel boolean not null default true,
  previsao_devolucao date,
  observacoes text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint veiculos_caucoes_pagamento_check check (
    (forma_pagamento in ('credito_avista', 'credito_parcelado') and cartao_id is not null and conta_id is null)
    or (forma_pagamento not in ('credito_avista', 'credito_parcelado') and conta_id is not null and cartao_id is null)
  ),
  constraint veiculos_caucoes_devolucao_check check (devolvivel or previsao_devolucao is null)
);

create unique index veiculos_caucoes_ativo_aluguel_idx
  on public.veiculos_caucoes (aluguel_id) where ativo;

alter table public.saidas
  add column veiculo_id bigint references public.veiculos(id) on delete restrict,
  add column financiamento_id bigint references public.veiculos_financiamentos(id) on delete restrict,
  add column aluguel_id bigint references public.veiculos_alugueis(id) on delete restrict,
  add column caucao_id bigint references public.veiculos_caucoes(id) on delete restrict,
  add column referencia_contrato integer;

create index idx_saidas_veiculo_id on public.saidas (veiculo_id);
create index idx_saidas_financiamento_id on public.saidas (financiamento_id);
create index idx_saidas_aluguel_id on public.saidas (aluguel_id);
create index idx_saidas_caucao_id on public.saidas (caucao_id);
create unique index saidas_financiamento_parcela_unique_idx
  on public.saidas (financiamento_id, referencia_contrato)
  where financiamento_id is not null and referencia_contrato is not null;
create unique index saidas_aluguel_vencimento_unique_idx
  on public.saidas (aluguel_id, data_vencimento)
  where aluguel_id is not null and data_vencimento is not null;
create unique index saidas_caucao_unique_idx
  on public.saidas (caucao_id) where caucao_id is not null;

create table public.veiculos_cobrancas_geradas (
  id bigint generated by default as identity primary key,
  veiculo_id bigint not null references public.veiculos(id) on delete restrict,
  financiamento_id bigint references public.veiculos_financiamentos(id) on delete restrict,
  aluguel_id bigint references public.veiculos_alugueis(id) on delete restrict,
  caucao_id bigint references public.veiculos_caucoes(id) on delete restrict,
  saida_id bigint references public.saidas(id) on delete set null,
  referencia integer,
  data_vencimento date,
  created_at timestamptz not null default now(),
  constraint veiculos_cobrancas_origem_check check (
    num_nonnulls(financiamento_id, aluguel_id, caucao_id) = 1
  )
);

create unique index veiculos_cobrancas_financiamento_unique_idx
  on public.veiculos_cobrancas_geradas (financiamento_id, referencia)
  where financiamento_id is not null;
create unique index veiculos_cobrancas_aluguel_unique_idx
  on public.veiculos_cobrancas_geradas (aluguel_id, data_vencimento)
  where aluguel_id is not null;
create unique index veiculos_cobrancas_caucao_unique_idx
  on public.veiculos_cobrancas_geradas (caucao_id)
  where caucao_id is not null;
create index idx_veiculos_cobrancas_saida_id on public.veiculos_cobrancas_geradas (saida_id);

comment on table public.veiculos_financiamentos is
  'Contrato de financiamento do veículo; parcelas pagas antes do ControlDriver são apenas referência histórica.';
comment on table public.veiculos_alugueis is
  'Contrato recorrente de aluguel vinculado ao veículo.';
comment on table public.veiculos_caucoes is
  'Caução de aluguel; quando devolvível, não representa custo definitivo automaticamente.';
comment on table public.veiculos_cobrancas_geradas is
  'Registro idempotente das cobranças criadas; permanece mesmo se o lançamento for excluído para impedir recriação automática.';
comment on column public.saidas.veiculo_id is
  'Vínculo financeiro direto com o veículo para composição de custos.';

grant select, insert, update, delete on table public.veiculos_financiamentos to anon, authenticated, service_role;
grant select, insert, update, delete on table public.veiculos_alugueis to anon, authenticated, service_role;
grant select, insert, update, delete on table public.veiculos_caucoes to anon, authenticated, service_role;
grant select, insert, update, delete on table public.veiculos_cobrancas_geradas to anon, authenticated, service_role;
grant usage, select on sequence public.veiculos_financiamentos_id_seq to anon, authenticated, service_role;
grant usage, select on sequence public.veiculos_alugueis_id_seq to anon, authenticated, service_role;
grant usage, select on sequence public.veiculos_caucoes_id_seq to anon, authenticated, service_role;
grant usage, select on sequence public.veiculos_cobrancas_geradas_id_seq to anon, authenticated, service_role;
